// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbnnmbgioasicwioyauw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNibm5tYmdpb2FzaWN3aW95YXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjE1MjAsImV4cCI6MjA2NzI5NzUyMH0.7TN_KF4JAtjDp1RKIboE1c79hPmkpCXPkiiEcaPFOeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});